In [1]:
import numpy as np
import numpy.linalg as lag

In [2]:
def is_zero(x): 
    return abs(x) < 1e-14

In [3]:
def pivot(M,i):
    em = "Error: pivot is zero"
    shape = np.shape(M)
    ec = True
    for n in range(i, shape[0]):
        if is_zero(M[n,i])==False:
            ec = False
    if ec == True:
        print(em)
        return i
    mv = 0
    p = 0
    for n in range(i,shape[0]):
        if abs(M[n,i])>mv:
            mv=abs(M[n,i])
            p = n    
    cm = M.copy()
    M[p,:] = cm[i,:]
    M[i,:] = cm[p,:]/cm[p,i]
    return(-1)

In [4]:
# B = np.random.randint(-10,30,size=(5,6)) * 1.0 used to generate B
B = np.array([[ 8., 14.,  -7.,  0., -5.,  8.],
              [ 4.,  8.,  25., -2.,  6., 27.],
              [21.,  0.,   3., -2., -7., 16.],
              [13.,  3.,   6., 21.,  4., 23.],
              [20.,  0.,  -8., 12.,  4., -2.]])
C = np.array([[ 8., 14.,  -7.,  0., -5.,  8.],
              [ 4.,  8.,  25., -2.,  6., 27.],
              [21.,  0.,   0., -2., -7., 16.],
              [13.,  3.,   0., 21.,  4., 23.],
              [20.,  0.,   0., 12.,  4., -2.]])
# Now the pivoting
B_val = pivot(B,2)
C_val = pivot(C,2)
# B should have been modified and should be identical to B_result below
B_result = np.array([[ 8.  , 14.  , -7.  ,  0.  , -5.  ,  8.  ],
                     [ 4.  ,  8.  , 25.  , -2.  ,  6.  , 27.  ],
                     [-2.5 ,  0.  ,  1.  , -1.5 , -0.5 ,  0.25],
                     [13.  ,  3.  ,  6.  , 21.  ,  4.  , 23.  ],
                     [21.  ,  0.  ,  3.  , -2.  , -7.  , 16.  ]])
# C should not have been modified. C should be identical to C_result below. 
C_result = np.array([[ 8., 14., -7.,  0., -5.,  8.],
                    [ 4.,  8., 25., -2.,  6., 27.],
                    [21.,  0.,  0., -2., -7., 16.],
                    [13.,  3.,  0., 21.,  4., 23.],
                    [20.,  0.,  0., 12.,  4., -2.]]) 
assert B_val == -1
assert np.allclose(B,B_result)
assert C_val == 2
assert np.allclose(C,C_result)
# Note pivot(C,2) generates message "Error: pivot is zero" below. This is correct behaviour

Error: pivot is zero


In [5]:
def gauss(M,i):
    cm = M.copy()
    shape = np.shape(M)
    for n in range(shape[0]):
        M[n,:] = cm[n,:] - (M[n,i] * cm[i,:])
    M[i,:] = cm[i,:]
    return(-1)

In [6]:
B1 = np.array([[ 8.  , 14.  , -7.  ,  0.  , -5.  ,  8.  ],
               [ 4.  ,  8.  , 25.  , -2.  ,  6.  , 27.  ],
               [-2.5 , -0.  ,  1.  , -1.5 , -0.5 ,  0.25],
               [13.  ,  3.  ,  6.  , 21.  ,  4.  , 23.  ],
               [21.  ,  0.  ,  3.  , -2.  , -7.  , 16.  ]])
B1_val = gauss(B1,2)
# B1 has now been modified (via elementary row operations)
# B1 should now be the same as B1_result below
B1_result = np.array([[ -9.5 ,  14.  ,   0.  , -10.5 ,  -8.5 ,   9.75],
                      [ 66.5 ,   8.  ,   0.  ,  35.5 ,  18.5 ,  20.75],
                      [ -2.5 ,  -0.  ,   1.  ,  -1.5 ,  -0.5 ,   0.25],
                      [ 28.  ,   3.  ,   0.  ,  30.  ,   7.  ,  21.5 ],
                      [ 28.5 ,   0.  ,   0.  ,   2.5 ,  -5.5 ,  15.25]])
assert B1_val == -1
assert np.allclose(B1,B1_result)

In [7]:
def reduce_matrix(M):
    shape = np.shape(M)
    for i in range(0,shape[0]):
        if pivot(M,i) == -1:
            gauss(M,i)
        else:
            return(i)
    return(-1)

In [8]:
B2 = np.array([[ 8., 14.,  -7.,  0., -5.,  8.,  3.],
               [ 4.,  8.,  25., -2.,  6., 27., -1.],
               [21.,  0.,   3., -2., -7., 16., 11.],
               [13.,  3.,   6., 21.,  4., 23., -5.],
               [20.,  0.,  -8., 12.,  4., -2., 12.]])
B2_val = reduce_matrix(B2)
# B2 has now been reduced and should be the same as B2_result below
B2_result = np.array([[ 1.,  0.,  0.,  0.,  0., 0.20081312,  0.7470541 ],
                      [ 0.,  1.,  0.,  0.,  0., 0.59194741, -0.12856537],
                      [ 0.,  0.,  1.,  0.,  0., 1.25116973, -0.35013236],
                      [ 0.,  0.,  0.,  1.,  0., 0.79038592, -0.72034135],
                      [ 0.,  0.,  0.,  0.,  1., -1.37288388, 0.72548882]])
assert B2_val == -1
assert np.allclose(B2,B2_result)
# Column C2[:,3]  is a scalar multiple of column C2[:,1] in C2 
C2 = np.array([[ 8., 14.,  -7.,  7., -5.,  8.,  3.],
               [ 4.,  8.,  25.,  4.,  6., 27., -1.],
               [21.,  0.,   3.,  0., -7., 16., 11.],
               [13.,  3.,   6., 1.5,  4., 23., -5.],
               [20.,  0.,  -8.,  0.,  4., -2., 12.]])
C2_val = reduce_matrix(C2)
# This time the computation is aborted as pivot(C2,3) fails
assert C2_val == 3 
# Note that reduce_matrix(C2) should print the message "Error: pivot is zero" below. 

Error: pivot is zero


In [9]:
def my_solve(A,b):
    shape = np.shape(A)[0]
    M = np.empty((shape, shape + 1))
    M[0:shape, 0:shape] = A
    M[0:shape,shape] = list(b)
    result = reduce_matrix(M)
    if result == -1:
        ans = np.empty((shape,1))
        for z in range(shape):
            ans[z,0] = M[z,shape]
        return(ans)
    else:
        return(result)

In [10]:
A3 = np.array([[1.0, 2, -3], [2, -1, 4], [1, -1, 1]])
b3 = np.array([[9.0],[1],[0]])
x3 = my_solve(A3,b3)
# x3 should now be the solution of this system. 
print("x3 = \n", x3, "\n")
assert np.allclose(x3,lag.solve(A3,b3))
# There is not a unique solution for the following system
B3 = np.array([[1.0, 2, -3], [2, -1, 4], [3.0, 6, -9]])
b3 = np.array([[9.0],[1],[0]])
y3 = my_solve(B3,b3)
# In fact pivot([B3|b3],2) failed during the computation
assert y3 == 2
# The message "Error: pivot is zero" should appear below 

x3 = 
 [[ 2.8]
 [ 2.2]
 [-0.6]] 

Error: pivot is zero


In [11]:
def my_inverse(M):
    shape = np.shape(M)[0]
    N = np.empty((shape, 2*shape))
    N[0:shape,0:shape] = M
    N[0:shape,shape:2*shape] = np.identity(shape)
    ans = reduce_matrix(M)
    if ans != -1:
        return(ans)
    else:
        inv = N[0:shape,shape:2*shape]
        print(inv)
        return(inv)

In [12]:
#A4 = np.random.randint(-10,30,size=(4,4)) * 1.0
A4 = np.array([[12.,  5., 24., 29.],
               [ 1., 16.,  9., -2.],
               [ 8.,  9., -5., -4.],
               [ 0., -5.,  4.,  3.]])
A4_inv = my_inverse(A4)
assert np.allclose(np.dot(A4,A4_inv), np.eye(4))
# B4 is not invertible 
B4 = np.array([[12.,  5., 24., -6.],
               [ 1., 16.,  9., -.5],
               [ 8.,  9., -5., -4.],
               [ 0., -5.,  4.,  0.]])
B4_inv = my_inverse(B4)
# In fact pivot([B4|I],3) failed during the computation
assert B4_inv == 3
assert my_inverse(np.zeros((7,7))) == 0 
# The message  below "Error: pivot is zero" should appear twice below. 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Error: pivot is zero
Error: pivot is zero
